"""Fig. 68 - McCabe-Thiele construction, stepped by algorithm.

Binary distillation stage count for a constant-relative-volatility
system: equilibrium curve y = ax/(1+(a-1)x), rectifying and stripping
operating lines, a sloped q-line, and the staircase generated by the
actual stepping algorithm (horizontal to equilibrium, vertical to the
active operating line) rather than drawn by hand. Stages are numbered
and the feed stage identified automatically.
"""

import numpy as np
import matplotlib.pyplot as plt

import journal_style as js

js.apply()
HERE = js.HERE

# ------------------------------------------------------ specification ----
ALPHA = 2.5
ZF, XD, XB = 0.50, 0.92, 0.06
R, Q = 1.8, 0.8                                   # reflux ratio, feed quality


def y_eq(x):
    return ALPHA * x / (1 + (ALPHA - 1) * x)


def x_eq(y):
    return y / (ALPHA - (ALPHA - 1) * y)


# operating lines
m_rect, b_rect = R / (R + 1), XD / (R + 1)
m_q, b_q = Q / (Q - 1), ZF - ZF * Q / (Q - 1)     # q-line through (zF, zF)
x_int = (b_q - b_rect) / (m_rect - m_q)           # rectifying x q-line
y_int = m_rect * x_int + b_rect
m_strip = (y_int - XB) / (x_int - XB)
b_strip = XB - m_strip * XB


def y_op(x):
    return np.where(x > x_int, m_rect * x + b_rect, m_strip * x + b_strip)


# -------------------------------------------------- stepping algorithm ----
corners = [(XD, XD)]
x, y = XD, XD
feed_stage, n = None, 0
while x > XB and n < 30:
    n += 1
    x_new = x_eq(y)                               # horizontal to equilibrium
    corners.append((x_new, y))
    if feed_stage is None and x_new < x_int:
        feed_stage = n
    x = x_new
    if x <= XB:
        break
    y = float(y_op(x))                            # vertical to operating line
    corners.append((x, y))
corners = np.array(corners)

# ------------------------------------------------------------- PLOT ----
fig, ax = plt.subplots(figsize=(3.7, 3.6))
ax.set_aspect("equal")
xx = np.linspace(0, 1, 400)

ax.plot([0, 1], [0, 1], color="0.6", lw=0.8)
ax.plot(xx, y_eq(xx), color="C0", lw=1.3)
ax.plot([XB, x_int], [XB, y_int], color="C2", lw=1.1)
ax.plot([x_int, XD], [y_int, XD], color="C1", lw=1.1)
xq = np.linspace(ZF, x_int, 50)
ax.plot(xq, m_q * xq + b_q, ls="--", lw=0.9, color="0.35")
ax.plot(corners[:, 0], corners[:, 1], color="black", lw=0.8)

# stage numbers at the horizontal steps
for k, i in enumerate(range(1, corners.shape[0], 2), start=1):
    x0, y0 = corners[i]
    x1 = corners[i - 1][0]
    ax.text((x0 + x1) / 2, y0 + 0.014, str(k), ha="center", va="bottom",
            fontsize=6)

for xv, lab in [(XB, "$x_B$"), (ZF, "$z_F$"), (XD, "$x_D$")]:
    ax.plot([xv, xv], [0, xv], ls=":", lw=0.6, color="0.6")
    ax.text(xv, -0.035, lab, ha="center", va="top", fontsize=8)

ax.annotate(f"feed stage = {feed_stage}", (x_int, y_int), xytext=(26, -26),
            textcoords="offset points", fontsize=7, ha="left", va="top",
            arrowprops=dict(arrowstyle="-|>", lw=0.7, color="0.3"))
ax.text(0.04, 0.975, f"$\\alpha$ = {ALPHA},  $R$ = {R},  $q$ = {Q}\n"
        f"$N$ = {n} stages (incl. reboiler)", fontsize=7, va="top")
ax.text(0.508, 0.560, "$q$-line", fontsize=7, color="0.35",
        rotation=-76, ha="left")
ax.text(0.76, 0.845, "rectifying", fontsize=7, color="C1", rotation=33)
ax.text(0.235, 0.245, "stripping", fontsize=7, color="C2", rotation=51)
ax.text(0.042, 0.235, "equilibrium", fontsize=7, color="C0",
        rotation=60, ha="left")

ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
ax.set_xlabel(r"liquid mole fraction, $x$")
ax.set_ylabel(r"vapour mole fraction, $y$")

for ext in ("png", "pdf"):
    fig.savefig(HERE / f"fig068_mccabe_thiele.{ext}")
print(f"saved fig068_mccabe_thiele.png / .pdf  (N = {n}, feed = {feed_stage})")
