"""Fig. 79 - CSTR steady-state multiplicity: the van Heerden diagram.

Heat generated by a first-order exothermic reaction in a CSTR,

    Q_gen(T) = x(T) = tau*k / (1 + tau*k),   tau*k = exp(A - E_R/T),

against the linear heat-removal line Q_rem = kappa (T - Tc). For the
middle coolant temperature the curves intersect three times: two stable
steady states (filled) and one unstable (open). The dashed lines are the
exact tangency cases, found by solving x'(T) = kappa with brentq: below
the ignition line the cold branch vanishes (the reactor lights off);
above the extinction line the hot branch vanishes. Illustrative
parameters.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import brentq

import journal_style as js

js.apply()
HERE = js.HERE

A_K, E_R = 25.0, 8000.0                            # ln(tau k0), E/R in K
KAPPA = 0.011                                      # removal slope, 1/K


def x_conv(T):
    tk = np.exp(A_K - E_R / T)
    return tk / (1.0 + tk)


def dx_dT(T):
    x = x_conv(T)
    return x * (1 - x) * E_R / T**2


# tangency (knee) temperatures: x'(T) = kappa on both flanks
T_KNEE_LO = brentq(lambda T: dx_dT(T) - KAPPA, 285, 319)
T_KNEE_HI = brentq(lambda T: dx_dT(T) - KAPPA, 321, 365)
TC_IGN = T_KNEE_LO - x_conv(T_KNEE_LO) / KAPPA
TC_EXT = T_KNEE_HI - x_conv(T_KNEE_HI) / KAPPA
TC_MID = 0.5 * (TC_IGN + TC_EXT)


def q_rem(T, tc):
    return KAPPA * (T - tc)


def steady_states(tc, lo=260, hi=384):
    Tg = np.linspace(lo, hi, 2000)
    f = x_conv(Tg) - q_rem(Tg, tc)
    k = np.flatnonzero(np.sign(f[:-1]) != np.sign(f[1:]))
    return [brentq(lambda T: x_conv(T) - q_rem(T, tc), Tg[i], Tg[i + 1])
            for i in k]


# ------------------------------------------------------------- PLOT ----
fig, ax = plt.subplots(figsize=(3.7, 3.0))
T = np.linspace(261, 385, 600)

ax.plot(T, x_conv(T), color="C1", lw=1.6, zorder=3)
ax.plot(T, q_rem(T, TC_MID), color="C0", lw=1.2, zorder=2)
for tc in (TC_IGN, TC_EXT):
    ax.plot(T, q_rem(T, tc), color="C0", lw=0.8, ls="--", zorder=2)

# steady states on the middle line: stable filled, unstable open
roots = steady_states(TC_MID)
for i, Ts in enumerate(roots):
    stable = i != 1
    ax.plot(Ts, x_conv(Ts), "o", ms=5, zorder=6,
            mfc="black" if stable else "white", mec="black", mew=1.1)

# ignition: tangency on the lower knee jumps to the hot branch
T_up = max(steady_states(TC_IGN))
ax.plot(T_KNEE_LO, x_conv(T_KNEE_LO), "o", ms=3.5, mfc="white", mec="0.35",
        mew=1.0, zorder=5)
ax.annotate("", xy=(T_up - 1.5, x_conv(T_up) - 0.02),
            xytext=(T_KNEE_LO + 1, x_conv(T_KNEE_LO) + 0.02),
            arrowprops=dict(arrowstyle="-|>", lw=0.8, color="0.4",
                            connectionstyle="arc3,rad=-0.25"))
ax.text(T_KNEE_LO + 4, x_conv(T_KNEE_LO) - 0.01, "ignition", fontsize=6.5,
        color="0.35", ha="left", va="top")

# extinction: tangency on the upper knee drops to the cold branch
T_dn = min(steady_states(TC_EXT))
ax.plot(T_KNEE_HI, x_conv(T_KNEE_HI), "o", ms=3.5, mfc="white", mec="0.35",
        mew=1.0, zorder=5)
ax.annotate("", xy=(T_dn + 1.5, x_conv(T_dn) + 0.02),
            xytext=(T_KNEE_HI - 1, x_conv(T_KNEE_HI) - 0.02),
            arrowprops=dict(arrowstyle="-|>", lw=0.8, color="0.4",
                            connectionstyle="arc3,rad=-0.25"))
ax.text(T_KNEE_HI - 4, x_conv(T_KNEE_HI) + 0.015, "extinction",
        fontsize=6.5, color="0.35", ha="right", va="bottom")

ax.text(294, 0.158, r"$Q_{gen}$", fontsize=8, color="C1",
        ha="right")
ax.text(338, 0.645, r"$Q_{rem} = \kappa(T - T_c)$",
        fontsize=7, color="C0", rotation=44, ha="center")
ax.text(0.03, 0.96, "\u25cf stable   \u25cb unstable",
        transform=ax.transAxes, fontsize=6.5, va="top")

ax.set_xlim(262, 385)
ax.set_ylim(0, 1.08)
ax.set_xlabel(r"reactor temperature, $T$ (K)")
ax.set_ylabel(r"dimensionless heat rate")

for ext in ("png", "pdf"):
    fig.savefig(HERE / f"fig079_cstr_multiplicity.{ext}")
print("saved fig079_cstr_multiplicity.png / .pdf")
